### ISSUE TITLE
🚧Improve update json version process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd-admin#21]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the version update process when updating versions for JSON files.  

> [!Note]
> This enhancement will only be for updating versions in JSON files.  Not csproj files.

Add a new property to the _**prepare-release-settings.json**_ settings file to hold the JSON key path to the version key.
The property name should be ~`jsonKeyPath`~ `versionJSONKeyPath` with a value of `string`.  Also, the setting/JSON property should be nullable in the interface to represent that the key is optional.  It is optional because it is not used or needed if the version file being used is a _**csproj**_ file.

If the type of file being used is indeed a JSON file, the ~`jsonKeyPath`~ `versionJSONKeyPath` is only required if the JSON key name is either not the name `version` or is not at the first level of the JSON tree.

### Examples of needing the ~`jsonKeyPath`~ `versionJSONKeyPath` setting

<details><summary>Details</summary>
<p>

Not required:
```json
{
    "version": "v1.2.3"
}
```

Required:
```json
{
    "app-version": "v1.2.3"
}
```

Required:
```json
{
    "app": {
          "appName": "my-app",
          "version": "1.2.3-preview.4"
      },
}
```

Required:
```json
{
    "app": {
          "appName": "my-app",
          "app-version": "1.2.3-preview.4"
      },
}
```

</p>
</details> 

The JSON key path will be a period-separated list of names, each name a JSON key. Each period represents another level in the JSON tree to get to the version key that needs to have its value updated.

**Example:**
```json
{
    "package": {
        "productName": "my-app",
        "version": "1.2.3-preview.4"
    },
}
```

In this JSON file, the key path would be `package.version`.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] New optional property with the name `versionJSONKeyPath` added to the `PrepareReleaseSettings` interface
- [x] Logic changed to use the new `versionJSONKeyPath` property for JSON version updates
- [x] An error is thrown if the `versionFilePath` is used but the `versionJSONKeyPath` is or is not used and the JSON key cannot be found.
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
