### ISSUE TITLE
🚧Move dev tool settings

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd-admin#27]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When generating and using dev tool settings, generate and reference them inside of the _**./dev-tools**_ directory.  This will keep everything together and make for a cleaner project setup.

1. Generatring settings file should be generated inside of the dev-tools folder
2. Referencing settings file in the install script should reference them inside of the dev-tools folder
3. When running the _**create-pr**_ process, it should reference the settings in the dev-tools folder
4. When running the _**prepare-release**_ process, it should reference the settings int he dev-tools folder

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Settings are generated in the _**dev-tools**_ folder
- [x] Settings are referenced in the _**dev-tools**_ folder in the install script
- [x] Settings are referenced in the _**dev-tools**_ during the _**create-pr**_ process
- [x] Settings are referenced in the _**dev-tools**_ the _**prepare-release**_ process
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
