### ISSUE TITLE
🚧Improve logging

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd-admin#44]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve logging throughout the application

**Improve logging in `release-prepper.ts`**
In the release prepper, there are various logs to the console that need improvement.  

An example of the current log:
`ConsoleLogColor.red("The assignee (github login) does not exist.");`

This log has the text '(gitub login)' but it should be the name of the actual login name.  This must of been filler text and was never finished.

So if the login was 'KinsonDigital', then the log message should be:
`The assignee 'KinsonDigital' does not exist`

Find all log messages like this in the _**release-prepper.ts**_ file and update them.

**Improve logging in `JsonVersionUpdater` class:**

Improve the log message when the version JSON key path cannot be found.  For example, when the `versionJSONKeyPath` value in the prepare release settings json config file is `package.version`, but the file that contains the version does not contain a json key with the name `package`, an error will be logged into the console like shown below:
`The property 'package' does not exist.`

This is not informative.  Update the message to show the name or path to the file that is missing the key value.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The logging in the release prepper class has been updated
- [ ] The logging in the json version updater has been updated
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
