### ISSUE TITLE
🚧Create install script

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd-admin#5]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create an install script that can be executed from a local machine to "install" the cli app.

This will perform various tasks such as ask the user for information such as which version to install, which target to compile the app to, setup the PATH environment variable for easy execution, ask for token setup, compile the script into an executable, and copy the end resulting compiled executable to the program files directory.

**Version Choice:**
When it comes to choosing a version, the script will use cliffy to ask the user which version they want to install.  This will be a list for the user to choose from with a search field which the list will consist of tag names, which will be versions.

**PAT Setup:**
PAT setup will be done by asking the user if they want to set this up.  If so, the script will ask the user for the token, which can be pasted or typed into the terminal.  The token will be hidden from view.  Once the token is entered, it will be saved as an environment variable with the name `KD_CLI_TOKEN`.

**Install Process:**
The install process will involve downloading the correct app  target based on which OS the script has detected to be executing on.  Once downloaded, the file will be renamed and copied to the correct installation directory

**Compilation:**
When it comes to compiling the app, the script will detect which operating system the script is being executed on and will compile the app to the correct target.

**Additional Changes:**
1. Prevent compilation of macOS targets. Do this by just commenting out the `compileTargetMonikers` code lines
2. Change the name of the compiled file to `kdcli`
3. Add the newly compiled file to a zip archive with the full incoming compile target as part of the name
    > **Note**
    > Zip File Name Example: kdcli-x86_64-pc-windows-msvc.zip
4. After compilation, delete the original compiled file name `kdcli`
5. Update the create GitHub release step in the release workflow to add each file separately.
    > **Note**
    > There were issues last time with all of the files being added to the release.  Perform testing to make sure that it works.
    > If it does not work, we might have to use the GitHub web API to add the files.  This means we would need to put this issue on hold and wait for the feature to be added to the `ReleaseClient` to have a feature added to the client to add and download files from releases.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Script asks the user which version to install
- [x] Script sets up the CLI app in the PATH environment variable
- [x] Script compiles the CLI app into an executable
- [x] Script asks and sets up a PAT for GitHub API access
- [x] macOS compilation disabled
- [x] compile file output name changed to `kdcli`
- [x] compiled file added to zip file
- [x] zip files are postfixed with target moniker
- [ ] release workflow updated
- [ ] Downloads the application from the GitHub releases
- [ ] ⚠️WARNING!! DO NOT FORGET AT THE VERY END⚠️Update `validate_release` release workflow job to fail if not correct branch
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without completion due to change in direction
